---
- src: jeremyltn.homebrew

- src: jeremyltn.dotfiles

- src: jeremyltn.git-repos

- src: jeremyltn.osx-computername

- src: jeremyltn.osx-oh-my-zsh

- src: jeremyltn.osx-php

- src: jeremyltn.osx-sudoers

- src: jeremyltn.remote-vars

- src: https://github.com/osxstrap/ansible-gitconfig.git
  name: jeremyltn.gitconfig

- src: https://github.com/osxstrap/ansible-osx-defaults.git
  name: jeremyltn.osx-defaults

- src: https://github.com/osxstrap/ansible-pip.git
  name: jeremyltn.pip

- src: https://github.com/osxstrap/ansible-include-vars-dir.git
  name: jeremyltn.include-vars-dir

- src: https://github.com/osxstrap/ansible-rbenv.git
  name: jeremyltn.rbenv

- src: https://github.com/osxstrap/ansible-ruby-gems.git
  name: jeremyltn.ruby-gems

- src: https://github.com/osxstrap/ansible-osx-node.git
  name: jeremyltn.osx-node