---
- hosts: all
  roles:
    - role: jeremyltn.include-vars-dir
      tags: ['common','always']
      include_vars_dir_paths:
        - "~/.config/osxstrap"
      include_vars_file_extension: "osxstrap"